### ISSUE TITLE
Some error exception handling

### ISSUE THREAD

**Issue by JPLanh** [HaroldAgnote/CECS-378#2]
Try adding some try/catch statement to deal with the error you get for inputting file names that does not exist, it might help avoid some headache for any mispelling of file names, and you wouldn't have to execute the program once again once you handle the error.

**Comment by HaroldAgnote** [comment]
Hey, Jimmy.
Thanks for the tip.
In some cases, I'm more in favor of using **assert **statements**** in order to determine that file names are inputted correctly. For our _payload.py_ and _MyUnlock.py_, we used them to ensure that the necessary files are there as needed and no errors occurred when connecting to the server.
